name: sugar_insights
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  supabase_flutter: ^1.10.25
  flutter_local_notifications: ^16.2.0
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.4
  video_player: ^2.10.0
  chewie: ^1.11.3
  share_plus: ^11.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/logo_icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/images/logo_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo_icon.png"

dependency_overrides:
  webview_flutter_android: ^3.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/sounds/

  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/lufga/LufgaRegular.ttf
        - asset: assets/fonts/lufga/LufgaBold.ttf
          weight: 700
        - asset: assets/fonts/lufga/LufgaMedium.ttf
          weight: 500
        - asset: assets/fonts/lufga/LufgaLight.ttf
          weight: 300 